---
title: "BSP_185 extended_Analyses_PigBAL"
author: "lily yang"
date: "`r Sys.Date()`"
output: html_document
---
# set up enrivonment and load data
```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
work_dir <- Sys.getenv("work_dir")
bsp_num <- Sys.getenv("bsp_num")
sampSet <- Sys.getenv("sampSet")
reference_genome_version <- Sys.getenv("reference_genome_version")
method = "edgeR"

if(reference_genome_version == "pig_113")
{
  entrez_map_file <- '/mnt/lustre/RDS-ephemeral/bioinformatics/analysis/scrna/proj/bsp_185/lily/stages/references/ensembl_entrez_map.csv' 

}
knitr::opts_knit$set(root.dir = work_dir)

```


```{r load library}


library(SingleCellExperiment)
library(DropletUtils)
library(viridisLite)  
library(DOSE)
library(pathview)
library(clusterProfiler)
library(org.Ss.eg.db)
library(ggplot2)
library(dplyr)

```


```{r import cell type annotation, prepare table need to use}

# obtain clusters id belong to same cell type
if(grepl("subset", sampSet))
{
  annot_file <- paste0("munual_annotation", sub("subset","", sampSet), ".csv")
  df_cell_type_cluster <- read.csv(annot_file, header = FALSE)  
}else
{
  df_cell_type_cluster <- read.csv("munual_annotation.csv", header = FALSE)  
}

colnames(df_cell_type_cluster) <- c('cluster', 'annotated_type')

# remove the content in parentheses as well as the parentheses
# df_cell_type_cluster$annotated_type <- sub(" \\(.*\\)", "", df_cell_type_cluster$annotated_type)

df_cell_type_cluster$annotated_type <- sub(" / ", " or ", df_cell_type_cluster$annotated_type)
df_cell_type_cluster$annotated_type <- sub("/", " or ", df_cell_type_cluster$annotated_type)


df_grouped <- df_cell_type_cluster %>%
  group_by(annotated_type) %>%
  summarise(cluster_numbers = paste(cluster, collapse = ", ")) %>%
  ungroup()

```


# enrichment analysis


```{r set functions}

draw_dot_plots_mul_cluster <- function(GO_multiple_cell_type, database = "GO", 
                                       kegg_immune = "", prefix = "_t1_t2_DPI12_",
                                       cell_type = selected_cell_types, EA_method= "over_represent")
{
  if(database == "GO")
  {
    colnames(GO_multiple_cell_type)[c(1, 2)] <- c('GO_ID', 'GO_description')
    ######################################## shorten a long GO term
    pos <- grep('superfamily', GO_multiple_cell_type$GO_description)
    if(length(pos) == 1)
    {
      GO_multiple_cell_type$GO_description[pos]  <- paste(GO_multiple_cell_type$GO_ID[pos],
                                                          "regulation of adaptive immune response")
      # GO_multiple_cell_type$GO_description[56]  <- "regulation of adaptive immune response based on somatic recombination of immune receptors built from immunoglobulin superfamily domains"
      
    }    
    ######################################## 
    
  }else if(database == "KEGG")
  {
    if(EA_method == "GSEA")
    {
      colnames(GO_multiple_cell_type)[c(1, 2)] <- c('KEGG_ID', 'KEGG_description')  
      
    }else
    {
      colnames(GO_multiple_cell_type)[c(3, 4)] <- c('KEGG_ID', 'KEGG_description')  
      
    }
  }
  
  
  
  GO_multiple_cell_type$named_cluster <- paste(GO_multiple_cell_type$cluster, GO_multiple_cell_type$cell_type, sep = ', ' )
  
  
  original_GO_multiple_cell_type = GO_multiple_cell_type
  
  
  
    
    # draw significant GO terms dot plot for multiple clusters in all cell types
    
    
    
    
    
    if(database == "GO")
    {
      # GO_multiple_cell_type <- GO_multiple_cell_type[(GO_multiple_cell_type$p.adjust < 0.01),]
      # length(unique(GO_multiple_cell_type$GO_ID))
      GO_multiple_cell_type$GO_description <- with(GO_multiple_cell_type, 
                                                   reorder(GO_description, GeneRatio_value))
      
      # draw dot plot for all cell types that have significant GO terms, including all GO terms
      p1 <- ggplot(data = GO_multiple_cell_type, aes(x = named_cluster, y = GO_description, 
                                                     color = `p.adjust`, size = GeneRatio_value)) + 
        geom_point() +
        scale_color_gradient(low = "red", high = "blue") +
        scale_size_continuous(limits = c(min(GO_multiple_cell_type$GeneRatio_value),
                                         max(GO_multiple_cell_type$GeneRatio_value)), range = c(3, 7)) + 
        theme_bw() + 
        ylab("") + theme(axis.text.x = element_text(angle = 90)) + 
        xlab("") + facet_grid(~ cell_type, scales = "free_x", space = "free_x") +
        ggtitle(paste(prefix, EA_method, database, "enrichment dot plot for cell type: ", cell_type)) 
      
      
      if(EA_method == "GSEA")
      {
        p1 <- p1 + labs(size = "geneset Size")
      }
      
      print(p1)
      
      
      png(filename=paste0('Results/EA_edgeR_', sampSet, "_BP_", database, "database_dotplot_mul_clusters", prefix , '_', cell_type, '_', EA_method, '.png'), height=9000, width=4000, res = 300)
      print(p1)
      dev.off()
      
      ######################################## 
      # # draw a bubble plot that only contain shared sig GO across 3 cell types
      # 
      # library(dplyr)
      # 
      # 
      # # Group by 'GO_ID' and count the number of unique cell types for each 'GO_ID'
      # shared_GO_IDs <- original_GO_multiple_cell_type %>%
      #   group_by(GO_ID) %>%
      #   filter(n_distinct(cell_type) == 3)  # Only keep GO_IDs with all 3 cell types
      # 
      # shared_GO_IDs$GO_description <- with(shared_GO_IDs, 
      #                                      reorder(GO_description, GeneRatio_value))
      # head(shared_GO_IDs)
      # write.table(shared_GO_IDs, paste0("Results/", sampSet, "_BP", "_edgeR_GO_dotplot_mul_clusters_shared.tsv"), sep="\t", quote=FALSE, row.names = FALSE)
      # 
      # 
      # # draw dot plot for all cell types that have significant GO terms, only including shared GO terms
      # p1 <- ggplot(data = shared_GO_IDs, aes(x = named_cluster, y = GO_description, 
      #                                        color = `p.adjust`, size = `GeneRatio_value`)) + 
      #   geom_point() +
      #   scale_color_gradient(low = "red", high = "blue") +
      #   theme_bw() + 
      #   ylab("") + theme(axis.text.x = element_text(angle = 90)) + 
      #   xlab("") + facet_grid(~ cell_type, scales = "free_x", space = "free_x") +
      #   ggtitle("shared GO enrichment dot plot per cell type")
      # 
      # # print(p1)
      # png(filename=paste0('Results/', sampSet, '_', DE_method, '_GO_dot_plot_mul_clusters_shared.png'), height=1080, width=1080, res = 120)
      # print(p1)
      # dev.off()
      # 
      # 
      # ######################################## 
      # # draw a bubble plot that only contain clusters within B cell main population
      # uniq_combined_GO_sig = original_GO_multiple_cell_type
      # uniq_combined_GO_sig <- uniq_combined_GO_sig[uniq_combined_GO_sig$cell_type == 'BCells' , ] 
      # #  Filter GO displayed in the plot by Gene ratio for B cell, only keep Gene ratio above 0.3 for B cell and then draw the dot plots again
      # # uniq_combined_GO_sig <- uniq_combined_GO_sig[uniq_combined_GO_sig$GeneRatio_value > 0.3 ,]                   
      # # Reorder the GO_description factor based on GeneRatio_value
      # uniq_combined_GO_sig$GO_description <- with(uniq_combined_GO_sig, 
      #                                             reorder(GO_description, GeneRatio_value))
      # # draw dot plot for all cell types that have significant GO terms
      # p1 <- ggplot(data = uniq_combined_GO_sig, aes(x = named_cluster, y = GO_description, 
      #                                               color = `p.adjust`, size = GeneRatio_value)) + 
      #   geom_point() +
      #   scale_color_gradient(low = "red", high = "blue") +
      #   theme_bw() + 
      #   ylab("") + 
      #   xlab("") + theme(axis.text.x = element_text(angle = 90)) + 
      #   ggtitle("GO enrichment dot plot for B cell population")
      # # scale_size_continuous(limits = c(0.3, max(uniq_combined_GO_sig$GeneRatio_value)), range = c(1, 7)) + 
      # png(filename=paste0('Results/', sampSet, '_', DE_method,'_GO_dot_plot_B_cell_mul_clusters.png'), height=9000, width=4000, 
      #     res = 300)
      # 
      # 
      # print(p1)
      # dev.off()
      # 
    }
    
    if(database == "KEGG")
    {
      GO_multiple_cell_type$KEGG_description <- with(GO_multiple_cell_type, 
                                                     reorder(KEGG_description, GeneRatio_value))
      # GO_multiple_cell_type$cell_type
      # print(table(GO_multiple_cell_type$cell_type))
      # GO_multiple_cell_type$cell_type <-  gsub("Macrophages", "M", GO_multiple_cell_type$cell_type)
      # print(table(GO_multiple_cell_type$cell_type))
      
      # draw dot plot for all cell types that have significant GO terms, including all GO terms
      p1 <- ggplot(data = GO_multiple_cell_type, aes(x = named_cluster, y = KEGG_description, 
                                                     color = `p.adjust`, size = GeneRatio_value)) + 
        geom_point() +
        scale_color_gradient(low = "red", high = "blue") +
        scale_size_continuous(limits = c(min(GO_multiple_cell_type$GeneRatio_value),
                                         max(GO_multiple_cell_type$GeneRatio_value)), range = c(3, 7)) + 
        theme_bw() + 
        ylab("") + theme(axis.text.x = element_text(angle = 90)) + 
        xlab("") + facet_grid(~ cell_type, scales = "free_x", space = "free_x") +
        ggtitle(paste(prefix, EA_method,  database, "enrichment dot plot for cell type: ", cell_type))  
      
      print(p1)
      png(filename=paste0('Results/EA_edgeR_', sampSet, "_BP_", database, 
                          "database_dotplot_mul_clusters",  prefix , '_', cell_type, '_', EA_method, '.png'), height=1400, width=1300, res = 150)
      
      print(p1)
      dev.off()
      
      ######################################## 
      # draw a bubble plot that only contain shared sig GO across 3 cell types
      
      # Group by 'GO_ID' and count the number of unique cell types for each 'GO_ID'
      # shared_GO_IDs <- GO_multiple_cell_type %>%
      #   group_by(KEGG_ID) %>%
      #   filter(n_distinct(cell_type) == 4)  # Only keep GO_IDs with all 3 cell types
      # if(nrow(shared_GO_IDs) == 0)
      # {
      #   print(paste("no shared KEGG pathways in 4 main populations", kegg_immune))
      #   return(shared_GO_IDs)
      # }
      # 
      # head(GO_multiple_cell_type)
      # table(GO_multiple_cell_type$cell_type)
      # shared_GO_IDs$KEGG_description <- with(shared_GO_IDs,
      #                                        reorder(KEGG_description, GeneRatio_value))
      # head(shared_GO_IDs)
      # if(kegg_immune == "")
      # {
      #   write.table(shared_GO_IDs, paste0("Results/", sampSet, "_BP", "_edgeR_KEGG_dotplot_mul_clusters_shared.tsv"), sep="\t", quote=FALSE, row.names = FALSE)
      #   
      # }else
      # {
      #   write.table(shared_GO_IDs, paste0("Results/", sampSet, "_BP", "_edgeR_KEGG", kegg_immune, "_dotplot_mul_clusters_shared.tsv"), sep="\t", quote=FALSE, row.names = FALSE)
      #   
      # }
      # 
      # 
      # # draw dot plot for all cell types that have significant GO terms, only including shared GO terms
      # p1 <- ggplot(data = shared_GO_IDs, aes(x = named_cluster, y = KEGG_description,
      #                                        color = `p.adjust`, size = `GeneRatio_value`)) +
      #   geom_point() +
      #   scale_color_gradient(low = "red", high = "blue") +
      #   theme_bw() +
      #   ylab("") + theme(axis.text.x = element_text(angle = 90)) +
      #   xlab("") + facet_grid(~ cell_type, scales = "free_x", space = "free_x") +
      #   ggtitle(paste("shared KEGG enrichment dot plot per cell type", kegg_immune))
      # 
      # # print(p1)
      # png(filename=paste0('Results/', sampSet, '_', DE_method, '_KEGG', kegg_immune, '_dot_plot_mul_clusters_shared.png'), height=1080, width=1080, res = 120)
      # print(p1)
      # dev.off()
      
      
      
    }    
  
}



combined_GO_dotplots_mul_cluster <- function(clusters = c("1", "9c"), 
                                             GO_multiple_cell_type,
                                             cell_type = "CD8T", DE_method = "edgeR", 
                                             EA_method= "over_represent",
                                             universal_file_path = 'run_2_edgeR_DE_cluster_',
                                             combine_flag = TRUE, database = "GO",
                                             id_type = "symbol")
{
  # print(paste('start run function combined_GO_dotplots_mul_cluster for', cell_type))
  combined_GO_sig_df <- NULL  
  # combined_GO_sig_df include sig_  GO terms or kegg category within one main population
  file_list <- paste0(paste0(universal_file_path, clusters),'.csv')
  names(file_list) <- clusters
  
  if(id_type == "entrez" & grepl("pig", reference_genome_version))
  {
    # only bsp185 use id_type= "entrez"
    entrez_map <- read.csv(file = '/mnt/lustre/RDS-ephemeral/bioinformatics/analysis/scrna/proj/bsp_185/lily/stages/references/ensembl_entrez_map.csv')
  }
  
  # iterate all clusters within one main population
  for (i in 1:length(file_list)) 
  {
    # generate correct input for EA command, like gseKEGG
    
    # import one DE table of a cluster
    file_path = file_list[i]
    
    if(file.exists(file_path))
    {
      print(paste('import DE results from file ', file_list[i]))
      res_ids = read.csv(file_path, header=TRUE)
      # head(res_ids)
    }else
    {
      print(paste('DE results for ', file_list[i], 'not exist, skip'))
      next
    }
    
    # head(res_ids_entrez)
    if(id_type == "entrez")
    {
      res_ids_entrez <- merge(res_ids, entrez_map[,c("entrez_ids", "ensembl_gene_id")], by.x= "ensemble_id",
                              by.y = "ensembl_gene_id", all.x = TRUE)
      table(is.na(res_ids_entrez$entrez_ids))     
      # head(res_ids_entrez)
    }
    
    
    # conduct enrichment analysis
    # prepare input data need for EA command
    if(EA_method == "over_represent")
    {
      if(id_type == "entrez")
      {
        all_ENTREZID <- as.character(res_ids_entrez$entrez_ids)
        print(paste("length (all_ENTREZID):", length(all_ENTREZID), "unique all_ENTREZID:", length(unique(all_ENTREZID)), ".", file_path)  )
        
        print(table(is.na(all_ENTREZID)))
        
        library(dplyr)
        ## Extract significant DE results
        sig_ENTREZID <- dplyr::filter(res_ids_entrez, p_adjust < 0.05)
        head(sig_ENTREZID)
        if(nrow(sig_ENTREZID) == 0)
        {
          print(paste("no sig DE genes for cluster ", file_path))
          next
        }
        sig_ENTREZID <- as.character(sig_ENTREZID$entrez_ids)         
      }else if(id_type == "symbol")
      {
        all_symbol <- as.character(res_ids$symbol)
        # print(table(is.na(all_symbol)))
        
        ## Extract significant DE results
        sig_symbol <- dplyr::filter(res_ids, p_adjust < 0.05)
        sig_symbol <- as.data.frame(sig_symbol)
        # sig_symbol <- dplyr::filter(res_ids, PValue < 0.05)
        # print(sig_symbol)
        # print(nrow(sig_symbol))
        if(nrow(sig_symbol) == 0 )
        {
          print(paste("no sig DE genes for cluster ", file_path, ', skip over_represent method'))
          next
        }
        sig_symbol <- as.character(sig_symbol$symbol)    
        # sometimes the only DEG doesn't have matched ENTREZID, so sig_ENTREZID will become empty, then don't continue over-present strategy

        sig_ENTREZID <- tryCatch({
          mapIds(org.Ss.eg.db,
                 keys     = sig_symbol,
                 column   = "ENTREZID",
                 keytype  = "SYMBOL",
                 multiVals = "first")
        }, error = function(e) {
          print("no valid ENTREZID for DEG, skip over_represent method")
          NULL
        })     
        if (is.null(sig_ENTREZID)) {
        
          next   
        }        
  
        sig_ENTREZID <- as.character(sig_ENTREZID)   
        sig_ENTREZID <- sig_ENTREZID[!is.na(sig_ENTREZID)]
        all_ENTREZID <- mapIds(org.Ss.eg.db,
                               keys=all_symbol,
                               column="ENTREZID",
                               keytype="SYMBOL",
                               multiVals = "first")
        
        all_ENTREZID <- as.character(all_ENTREZID)
        all_ENTREZID <- all_ENTREZID[!is.na(all_ENTREZID)]
        print(paste("length of all_ENTREZID:", length(all_ENTREZID), "length of sig_ENTREZID:", length(sig_ENTREZID), ";", file_path)  )
        if(length(sig_ENTREZID) == 0)
        {
          print("valid sig_ENTREZID is 0, skip")
          next
        }
      }      
    }
    
      ## Create background dataset for hypergeometric testing using all genes tested for significance in the results                 
      ## Extract significant DE results   

      
    if(EA_method == "GSEA")
    {
      # sort gene order
      geneList_df <- res_ids[, c("logFC", "symbol") ]
      ENTREZID <- mapIds(org.Ss.eg.db,
                         keys=geneList_df$symbol,
                         column="ENTREZID",
                         keytype="SYMBOL",
                         multiVals = "filter") 
      ENTREZID <- as.data.frame(ENTREZID)
      
      ENTREZID$symbol <- rownames(ENTREZID)
      # print(ENTREZID[is.na(ENTREZID$ENTREZID) , ])
      geneList_df <- merge(geneList_df, ENTREZID, all.x = TRUE)
      # remove esemble id without paired ENTREZID found
      geneList_df <- geneList_df[!is.na(geneList_df$ENTREZID) , ]
      head(geneList_df)
      nrow(geneList_df)
      length(unique(geneList_df$ENTREZID))
      library(dplyr)
      # length(unique(geneList_df$ENTREZID))
      geneList_df <- geneList_df %>%
        group_by(ENTREZID) %>%
        sample_n(1) %>%
        ungroup()
      geneList_df <- as.data.frame(geneList_df)
      ## feature 1: numeric vector
      geneList = geneList_df[, "logFC"]
      names(geneList) = as.character(geneList_df[, "ENTREZID"]) 
      ## feature 2: named vector
      head(geneList)
      ## feature 3: decreasing order
      geneList = sort(geneList, decreasing = TRUE)
    }
      
    if(database == "GO")
    {
      if(EA_method == "over_represent")
      {
      # print(paste0("enough DE genes",length(sigOE_genes), file_path))
      ## Run GO enrichment analysis, GO over-representation analysis 
      ego <- enrichGO(gene = sig_ENTREZID, 
                      universe = all_ENTREZID,
                      OrgDb = org.Ss.eg.db, 
                      keyType = "ENTREZID",
                      ont = "BP", 
                      pAdjustMethod = "fdr",
                      readable = TRUE)             
      }else if(EA_method == "GSEA")
      {
        
        ego <- gseGO(geneList     = geneList,
                      OrgDb        = org.Ss.eg.db,
                     keyType = "ENTREZID",
                      ont          = "BP",
                      minGSSize    = 100,
                      maxGSSize    = 500,
                      pvalueCutoff = 0.05,
                     pAdjustMethod = "fdr",
                      verbose      = FALSE)
      }
     
        
        # keyType = "ncbi-geneid",
      if(is.null(ego))
      {
        print(paste("ego is null", database, EA_method, file_path))
        next
      }
        GO_result_df <- ego@result
        if(sum(GO_result_df$pvalue < 0.05) == 0)
        {
          print(paste("no enriched GO (pvalue < 0.05) in Gene Ontology (GO) database", file_path))
          next
        }
        # remove GO terms with less than 3 DEGs annotated
        if(EA_method == "over_represent")
        {
          GO_result_df <- GO_result_df[(GO_result_df$Count >= 3) , ]    
          if(nrow(GO_result_df) == 0)
          {
            print(paste('no GO terms in Gene Ontology (GO) database with over 3 DEGs annotated for', file_path))
            next
          }            
        }
      
        # print(head(GO_result_df, 2))
        
      }
      
    if(database == "KEGG")
    {
      if(EA_method == "over_represent")
      {
      ## Run GO enrichment analysis, KEGG over-representation analysis 
      KEGG_ORA <- enrichKEGG(gene = sig_ENTREZID,
                             organism = 'ssc',  keyType = "ncbi-geneid",
                             universe = all_ENTREZID, pvalueCutoff = 0.05,
                             pAdjustMethod = "fdr",
                             qvalueCutoff = 0.2)         
      
      # 	KEGG only includes genes that are mapped to known pathways. If a gene in your background is not annotated in KEGG (e.g., novel genes or genes with unknown functions), it will not be used in the analysis.
      #	This is a common issue for non-model organisms like pigs, as the KEGG annotation for pigs may be incomplete compared to more studied species like humans or mice.
      
      
      

         
      }else if(EA_method == "GSEA")
      {
        KEGG_ORA <- gseKEGG(geneList= geneList,
                       organism     = 'ssc',
                       keyType = "ncbi-geneid",
                       minGSSize    = 120,
                       pvalueCutoff = 0.05,
                       verbose      = FALSE)


      }
      if(is.null(KEGG_ORA))
      {
        print(paste("KEGG_ORA is null",  EA_method, file_path))
        next
      }
      KEGG_ORA <- setReadable(KEGG_ORA, OrgDb = org.Ss.eg.db, keyType="ENTREZID")
      GO_result_df <- KEGG_ORA@result
      if(nrow(GO_result_df) == 0)
      {
        print(paste('KEGG_ORA is empty', EA_method, file_path))
        next
      }
    
    }
    
    
    
    # GO_result_df$p.adjust <- GO_result_df$pvalue
    # when we use pvalue instead of p.adjust value
    GO_result_df_sig <- GO_result_df[(GO_result_df$p.adjust < 0.05), ]
    # GO_result_df_sig <- GO_result_df[(GO_result_df$p.adjust < 0.1), ]
    
    if(nrow(GO_result_df_sig) == 0) 
    {
      print(paste('no significant hit for cluster ', file_path))
      next
    }     
    # print(paste(nrow(GO_result_df_sig), file_list[i]), names(file_list)[i])
    GO_result_df_sig$cell_type <- cell_type
    GO_result_df_sig$cluster <- names(file_list)[i]
    
    
    ######################################## 
    # check if there is a GO term contain superfamily which is too long
    pos <- grep('superfamily', GO_result_df_sig$Description)
    if(length(pos) == 1)
    {
      print('find it')
      print(GO_result_df_sig$Description[pos])
    }
    ######################################## 
    combined_GO_sig_df <- rbind(combined_GO_sig_df, GO_result_df_sig)
    
    
  }
  
  # obtain enriched GO across all cluster within one cell type
  if(is.null(combined_GO_sig_df)) 
  {
    print(paste('no enriched hit for all cluster within population: ', EA_method, database))
    return(GO_multiple_cell_type)
  }else
  {
    if(EA_method == "over_represent")
    {
    # uniq_combined_GO_sig <- uniq_combined_GO_sig[1:30,]
    # tranfer GeneRatio 25/150 into 0.1666667
    # Use strsplit to split the GeneRatio column by '/'
    split_values <- strsplit(combined_GO_sig_df$GeneRatio, "/")
    
    # Convert the split strings to numeric and perform the division
    combined_GO_sig_df$GeneRatio_value <- sapply(split_values, function(x) as.numeric(x[1]) / as.numeric(x[2]))
       
    }else if(EA_method == "GSEA")
    {
    combined_GO_sig_df$GeneRatio <- combined_GO_sig_df$setSize  
    combined_GO_sig_df$GeneRatio_value <- combined_GO_sig_df$setSize  
    }
   
    if(combine_flag == FALSE)
    {
      GO_multiple_cell_type <- rbind(GO_multiple_cell_type, combined_GO_sig_df)
      return(GO_multiple_cell_type)    
    }
    
    
  }
  
}


conduct_EA_main <- function(selected_DE_method, selected_prefix)
{
  selected_file_path <- paste0('Results/DE_', selected_DE_method, '_', sampSet, selected_prefix, '_cluster_')
  
  
  for (selected_cell_types in df_grouped$annotated_type) 
  {
    print(selected_cell_types)
    selected_Cluster <- as.character(df_grouped[df_grouped$annotated_type == 
                                                  selected_cell_types, "cluster_numbers"])
    selected_Cluster <-  strsplit(selected_Cluster, split = ", ")[[1]] 
    print(selected_Cluster)
    
    ################################################################
    selected_EA_method <- "over_represent"
    # Over Representation Analysis
    ################################################################
    selected_database <- "GO"
    print(paste("start selected_EA_method:", selected_EA_method, "selected_database:", selected_database))
    GO_multiple_cell_type <- NULL
    GO_multiple_cell_type <- combined_GO_dotplots_mul_cluster(clusters = selected_Cluster,
                                                              GO_multiple_cell_type,
                                                              database = selected_database,
                                                              cell_type = selected_cell_types,
                                                              DE_method = selected_DE_method,
                                                              EA_method = selected_EA_method,
                                                              universal_file_path = selected_file_path,
                                                              combine_flag = FALSE, id_type = "symbol")
    
    if(is.null(GO_multiple_cell_type))
    {
      print(paste("no hit in database", selected_database, "with method", EA_method))

    }else
    {
      write.table(GO_multiple_cell_type, paste0("Results/EA_", selected_DE_method, "_", sampSet,
                                                "_BP_", selected_database, "database_dotplot_mul_clusters",
                                                selected_prefix, selected_cell_types, "_", selected_EA_method, ".tsv"), sep="\t", quote=FALSE, row.names = FALSE)

      draw_dot_plots_mul_cluster(GO_multiple_cell_type, database = selected_database,
                                 cell_type = selected_cell_types, prefix= selected_prefix,
                                 EA_method = selected_EA_method)

    }
    ################################################################
    selected_database <- "KEGG"
    print(paste("start selected_EA_method:", selected_EA_method, "selected_database:", selected_database))    
    GO_multiple_cell_type <- NULL
    GO_multiple_cell_type <- combined_GO_dotplots_mul_cluster(clusters = selected_Cluster,
                                                              GO_multiple_cell_type,
                                                              database = selected_database,
                                                              cell_type = selected_cell_types,
                                                              DE_method = selected_DE_method,
                                                              EA_method = selected_EA_method,
                                                              universal_file_path = selected_file_path,
                                                              combine_flag = FALSE, id_type = "symbol")
    
    if(is.null(GO_multiple_cell_type))
    {
      print(paste("no hit in database", selected_database, "with method", EA_method))

    }else
    {
      write.table(GO_multiple_cell_type, paste0("Results/EA_", selected_DE_method, "_", sampSet,
                                                "_BP_", selected_database, "database_dotplot_mul_clusters",
                                                selected_prefix, selected_cell_types, "_", selected_EA_method, ".tsv"), sep="\t", quote=FALSE, row.names = FALSE)

      draw_dot_plots_mul_cluster(GO_multiple_cell_type, database = selected_database,
                                 cell_type = selected_cell_types, prefix= selected_prefix,
                                 EA_method = selected_EA_method)

    }

    ################################################################
    selected_EA_method <- "GSEA"
    # Gene Set Enrichment Analysis
    ################################################################    
    selected_database <- "GO"
    print(paste("start selected_EA_method:", selected_EA_method, "selected_database:", selected_database))    
    GO_multiple_cell_type <- NULL
    GO_multiple_cell_type <- combined_GO_dotplots_mul_cluster(clusters = selected_Cluster,
                                                              GO_multiple_cell_type,
                                                              database = selected_database,
                                                              cell_type = selected_cell_types,
                                                              DE_method = selected_DE_method,
                                                              EA_method = selected_EA_method,
                                                              universal_file_path = selected_file_path,
                                                              combine_flag = FALSE, id_type = "symbol")
    
    if(is.null(GO_multiple_cell_type))
    {
      print(paste("no hit in database", selected_database, "with method", EA_method))

    }else
    {
      write.table(GO_multiple_cell_type, paste0("Results/EA_", selected_DE_method, "_", sampSet,
                                                "_BP_", selected_database, "database_dotplot_mul_clusters",
                                                selected_prefix, selected_cell_types, "_", selected_EA_method, ".tsv"), sep="\t", quote=FALSE, row.names = FALSE)

      draw_dot_plots_mul_cluster(GO_multiple_cell_type, database = selected_database,
                                 cell_type = selected_cell_types, prefix= selected_prefix,
                                 EA_method = selected_EA_method)

    }
    ################################################################
    # KEGG GSEA doesn't accept repeat ncbi_id, but the conversion from 
    # symbol/ensemble_id to ncbi_id always induce repeats, so i add code randomly remain 1 ncbi_id for such situation
    # to conduct this analysis, better to use ncbi reference database in cell ranger count mapping step
    selected_database <- "KEGG"
    print(paste("start selected_EA_method:", selected_EA_method, "selected_database:", selected_database))    
    GO_multiple_cell_type <- NULL
    GO_multiple_cell_type <- combined_GO_dotplots_mul_cluster(clusters = selected_Cluster,
                                                              GO_multiple_cell_type,
                                                              database = selected_database,
                                                              cell_type = selected_cell_types,
                                                              DE_method = selected_DE_method,
                                                              EA_method = selected_EA_method,
                                                              universal_file_path = selected_file_path,
                                                              combine_flag = FALSE, id_type = "symbol")

    if(is.null(GO_multiple_cell_type))
    {
      print(paste("no hit in database", selected_database, "with method", EA_method))

    }else
    {
      write.table(GO_multiple_cell_type, paste0("Results/EA_", selected_DE_method, "_", sampSet,
                                                "_BP_", selected_database, "database_dotplot_mul_clusters",
                                                selected_prefix, selected_cell_types, "_", selected_EA_method, ".tsv"), sep="\t", quote=FALSE, row.names = FALSE)

      draw_dot_plots_mul_cluster(GO_multiple_cell_type, database = selected_database,
                                 cell_type = selected_cell_types, prefix= selected_prefix,
                                 EA_method = selected_EA_method)
    }

  }
}  



```




```{r draw 2 dot plots contain each cluster as one column, and group columns based on main cell population, using KEGG dataset , fig.width= 12}
save.image(file = paste0('EA_debug',sampSet,'.RData'))


conduct_EA_main(selected_DE_method = "edgeR", selected_prefix = "_H1N1_PRCV_DPI12")
conduct_EA_main(selected_DE_method = "edgeR", selected_prefix = "_H1N1_PRCV_DPI1")
 
# bsp248 don't have DE comparison for _ctl_PRCV_DPI12, _ctl_H1N1_DPI12
# conduct_EA_main(selected_DE_method = "edgeR", selected_prefix = "_ctl_PRCV_DPI12")
conduct_EA_main(selected_DE_method = "edgeR", selected_prefix = "_ctl_PRCV_DPI1")

# conduct_EA_main(selected_DE_method = "edgeR", selected_prefix = "_ctl_H1N1_DPI12")
conduct_EA_main(selected_DE_method = "edgeR", selected_prefix = "_ctl_H1N1_DPI1")
  


```

```{r draw 2 dot plots contain each cluster as one column, and group columns based on main cell population, using KEGG dataset and select only immune related KEGG ids}
# 
# library(readxl)
# setwd("/mnt/lustre/RDS-ephemeral/bioinformatics/analysis/scrna/proj/bsp_185/lily/stages/references/")
# file_path_selected_keggids <- c("run_2_edgeR_KEGG_dotplot_combined_WG_selected.xlsx",
#                                          "run_2_edgeR_KEGG_dotplot_combined_shared_WG_selected.xlsx")
# 
# selected_keggids <- NULL
# for (i in 1:length(file_path_selected_keggids))
# {
#   selected_keggi_df <- as.data.frame(read_excel(file_path_selected_keggids[i]) )
# 
#   head(selected_keggi_df)
#   selected_keggi_df <- selected_keggi_df[!is.na(selected_keggi_df$keep) , ]
#   print(length(selected_keggi_df$ID))
#   selected_keggids <- c(selected_keggids, selected_keggi_df$ID)
# }
# # length(selected_keggids)
# selected_keggids <- unique(selected_keggids)
# nrow(GO_multiple_cell_type)
# # table(GO_multiple_cell_type$ID %in% selected_keggids)
# 
# GO_multiple_cell_type <- GO_multiple_cell_type[(GO_multiple_cell_type$ID %in% selected_keggids) , ]
# nrow(GO_multiple_cell_type)
# # head(GO_multiple_cell_type)
# setwd(work_dir)
# 
# write.table(GO_multiple_cell_type, paste0("Results/", sampSet, "_BP", "_edgeR_KEGG_manual_select_dotplot_mul_clusters.tsv"), sep="\t", quote=FALSE, row.names = FALSE)
# 
# draw_dot_plots_mul_cluster(GO_multiple_cell_type, selected_database = "KEGG", kegg_immune = "manual_select")

```

```{r use enrichGO and plot combined GO dot plot include multiple cell types using edgeR DE results, fig.width= 10, fig.height=10}

# 
# 
# 
# combined_GO_dotplots_per_cell_type <- function(selected_cluster = c("1", "9c"), 
#                                                GO_multiple_cell_type,
#                                                cell_type = "CD8T", method = "edgeR", 
#                                                universal_file_path = 'run_2_edgeR_DE_cluster_',
#                                                combine_flag = TRUE)
# {
#   print(paste('start run function combined_GO_dotplots_per_cell_type for', cell_type))
#   combined_GO_sig_df <- NULL  
#   file_list <- paste0(paste0(universal_file_path, selected_cluster),'.csv')
#   names(file_list) <- selected_cluster
#   # file_path = '/mnt/rstudio/lily/bsp185/Results/run_2_edgeR_DE_cluster_1.csv'
#   
#   for (i in 1:length(file_list)) 
#   {
#     # import one DE table of a cluster
#     file_path <- file_list[i]
#     res_ids <- read.csv(file_path, header=TRUE)
# 
#     
#     
#     if(method == "edgeR")
#     {
#       
#       
#       ## Create background dataset for hypergeometric testing using all genes tested for significance in the results                 
#       allOE_genes <- as.character(res_ids$symbol)
#       
#       ## Extract significant DE results
#       sigOE <- dplyr::filter(res_ids, p_adjust < 0.05)
#       head(sigOE)
#       sigOE_genes <- as.character(sigOE$symbol)
#       
#       if(length(sigOE_genes) == 0)
#       {
#         # if there is 0 DE genes, skip this cluster
#         print(paste('no sigDE', file_path))
#         next
#       }
#       # print(paste0("enough DE genes",length(sigOE_genes), file_path))
#       ## Run GO enrichment analysis 
#       ego <- enrichGO(gene = sigOE_genes, 
#                       universe = allOE_genes,
#                       keyType = "SYMBOL",
#                       OrgDb = org.Ss.eg.db, 
#                       ont = "BP", 
#                       pAdjustMethod = "fdr", 
#                       qvalueCutoff = 0.05, 
#                       readable = TRUE)
#       
#       
#       # enrichment analysis using KEGG database
#       sig_ENTREZID <- mapIds(org.Ss.eg.db, 
#                              keys=sigOE_genes, 
#                              column="ENTREZID", 
#                              keytype="SYMBOL", 
#                              multiVals = "first")
#       KEGG_ORA <- enrichKEGG(gene = sig_ENTREZID,
#                              organism = 'ssc',
#                              pvalueCutoff = 0.05)
#       # KEGG_ORA <- enrichKEGG(gene = sig_ENTREZID,
#       #                  organism = 'ssc',  universe = allOE_genes,
#       #                  pvalueCutoff = 0.05)
#       head(KEGG_ORA)
#       KEGG_ORA <- setReadable(KEGG_ORA, OrgDb = org.Ss.eg.db, keyType="ENTREZID")
#       head(KEGG_ORA)
#       
#       
#     }
#     if(nrow(data.frame(ego)) == 0)
#     {
#       print(paste('no enriched GO', file_path))
#       next
#     }
#     GO_result_df <- ego@result
#     # print(head(GO_result_df))
#     
#     GO_result_df_sig <- GO_result_df[(GO_result_df$p.adjust < 0.05),]
#     GO_result_df_sig$cell_type <- cell_type
#     GO_result_df_sig$cluster <- names(file_list)[i]
#     combined_GO_sig_df <- rbind(combined_GO_sig_df, GO_result_df_sig)
#     
#     
#   }
#   
#   
#   if(is.null(combined_GO_sig_df)) 
#   {
#     print(paste('no enriched GO for all cluster within', cell_type))
#     return(GO_multiple_cell_type)
#   }else
#   {
#     # uniq_combined_GO_sig <- uniq_combined_GO_sig[1:30,]
#     # tranfer GeneRatio 25/150 into 0.1666667
#     # Use strsplit to split the GeneRatio column by '/'
#     split_values <- strsplit(combined_GO_sig_df$GeneRatio, "/")
#     
#     # Convert the split strings to numeric and perform the division
#     combined_GO_sig_df$GeneRatio <- sapply(split_values, function(x) as.numeric(x[1]) / as.numeric(x[2]))
#     
#     if(combine_flag == FALSE)
#     {
#       GO_multiple_cell_type <- rbind(GO_multiple_cell_type, combined_GO_sig_df)
#       return(GO_multiple_cell_type)    
#     }
#     
#     # uniq_combined_GO_sig <- aggregate(cbind(combined_GO_sig_df$p.adjust, combined_GO_sig_df$GeneRatio, combined_GO_sig_df$cell_type), by = list(combined_GO_sig_df$ID), FUN=min)
#     # Load dplyr package
#     library(dplyr)
#     
#     # Group by 'ID' and only remain row whose 'p.adjust' is the minimum within each group
#     uniq_combined_GO_sig <- combined_GO_sig_df %>%
#       group_by(ID) %>%
#       filter(p.adjust == min(p.adjust)) %>%
#       ungroup()  # Ungroup after the operation
#     
#     # View the result
#     # print(uniq_combined_GO_sig)
#     
#     colnames(uniq_combined_GO_sig)[c(1, 2, 3)] <- c('GO_ID', 'GO_description', 'corresponding_GeneRatio')
# 
#     colnames(uniq_combined_GO_sig)[colnames(uniq_combined_GO_sig)=="p.adjust"] <-  'min_p.adjust'
# 
#     # uniq_combined_GO_sig <- uniq_combined_GO_sig[, c(1, 2, 9, 3)]
#     uniq_combined_GO_sig$min_p.adjust <- as.numeric(uniq_combined_GO_sig$min_p.adjust)
#     uniq_combined_GO_sig$corresponding_GeneRatio <- as.numeric(uniq_combined_GO_sig$corresponding_GeneRatio)
#     GO_sig_per_cell_type <- uniq_combined_GO_sig
#     
#     if(cell_type == 'BCells')
#     {
#       #  Filter GO displayed in the plot by Gene ratio for B cell, only keep Gene ratio above 0.3 for B cell and then draw the dot plots again
#       if(sum(uniq_combined_GO_sig$corresponding_GeneRatio > 0.3) > 0)
#       {
#         uniq_combined_GO_sig <- uniq_combined_GO_sig[uniq_combined_GO_sig$corresponding_GeneRatio > 0.3 ,]                   
#         # Reorder the GO_description factor based on corresponding_GeneRatio
#         uniq_combined_GO_sig$GO_description <- with(uniq_combined_GO_sig, 
#                                                     reorder(GO_description, corresponding_GeneRatio))
#         # draw dot plot for all cell types that have significant GO terms
#         p1 <- ggplot(data = uniq_combined_GO_sig, aes(x = cell_type, y = GO_description, 
#                                                       color = `min_p.adjust`, size = corresponding_GeneRatio)) + 
#           geom_point() +
#           scale_color_gradient(low = "red", high = "blue") +
#           scale_size_continuous(limits = c(0.3, max(uniq_combined_GO_sig$corresponding_GeneRatio)), range = c(1, 7)) + 
#           theme_bw() + 
#           ylab("") + 
#           xlab("") + 
#           ggtitle("GO enrichment dot plot for B cell population")
#         
#         png(filename=paste0('Results/', sampSet, '_', method,'_GO_dot_plot_B_cell.png'), height=1080, width=900, 
#             res = 120)
#         print(p1)
#         dev.off()
#         
#       }
#       
#       
#     }
#     
#     
#     GO_multiple_cell_type <- rbind(GO_multiple_cell_type, GO_sig_per_cell_type)
#     return(GO_multiple_cell_type)
#     
#   }
#   
# }
# 



# GO_multiple_cell_type <- NULL
# 
# universal_file_path <- paste0('Results/', sampSet, '_edgeR_DE_cluster_')
# 
# if(sampSet == 'run_1' )
# {
#   GO_multiple_cell_type <- combined_GO_dotplots_per_cell_type(selected_cluster = c("2", "9a", "14a"),
#                                                               GO_multiple_cell_type,
#                                                               cell_type = "CD8T", method = "edgeR",
#                                                               universal_file_path = universal_file_path)
#   
#   
#   GO_multiple_cell_type <- combined_GO_dotplots_per_cell_type(selected_cluster = c("5", "10", "12c"),
#                                                               GO_multiple_cell_type,
#                                                               cell_type = "Macrophages", method = "edgeR", 
#                                                               universal_file_path = universal_file_path)
#   
#   GO_multiple_cell_type <- combined_GO_dotplots_per_cell_type(selected_cluster = c("3a", "14c", "17"),
#                                                               GO_multiple_cell_type,
#                                                               cell_type = "CD4T", method = "edgeR", 
#                                                               universal_file_path =universal_file_path)
#   
#   GO_multiple_cell_type <- combined_GO_dotplots_per_cell_type(selected_cluster = c("7", "13", '1', '4', '15'),
#                                                               GO_multiple_cell_type,
#                                                               cell_type = "BCells", method = "edgeR", 
#                                                               universal_file_path =universal_file_path)
#   
# }
# 
# if(sampSet == 'run_2' )
# {
#   GO_multiple_cell_type <- combined_GO_dotplots_per_cell_type(selected_cluster = c("1", "9c"),
#                                                               GO_multiple_cell_type,
#                                                               cell_type = "CD8T", method = "edgeR",
#                                                               universal_file_path = universal_file_path)
#   
#   
#   GO_multiple_cell_type <- combined_GO_dotplots_per_cell_type(selected_cluster = c("3", "6",  "20"),
#                                                               GO_multiple_cell_type,
#                                                               cell_type = "Macrophages", method = "edgeR", 
#                                                               universal_file_path = universal_file_path)
#   
#   GO_multiple_cell_type <- combined_GO_dotplots_per_cell_type(selected_cluster = c("4a", "8", "9a"),
#                                                               GO_multiple_cell_type,
#                                                               cell_type = "CD4T", method = "edgeR", 
#                                                               universal_file_path =universal_file_path)
#   
#   GO_multiple_cell_type <- combined_GO_dotplots_per_cell_type(selected_cluster = c('5', '10', '12', '13', '14',
#                                                                                    '18', "7", "17"),
#                                                               GO_multiple_cell_type,
#                                                               cell_type = "BCells", method = "edgeR", 
#                                                               universal_file_path =universal_file_path)
#   
#   
# }
# # head(GO_multiple_cell_type)
# write.table(GO_multiple_cell_type, paste0("Results/", sampSet, "_BP", "_edgeR_GO_dotplot_combined.tsv"), sep="\t", quote=FALSE, row.names = FALSE)
# 
# # draw dot plot for all cell types, and only keep significant GO terms shared across cell types
# if(sampSet == 'run_2' )
# {
#   # shorten a long GO term
#   pos <- grep('superfamily', GO_multiple_cell_type$GO_description)
#   if(length(pos) ==1)
#   {
#   GO_multiple_cell_type$GO_description[pos]  <- paste(GO_multiple_cell_type$GO_ID[pos],
#                                                       "regulation of adaptive immune response")
#   # GO_multiple_cell_type$GO_description[56]  <- "regulation of adaptive immune response based on somatic recombination of immune receptors built from immunoglobulin superfamily domains"
#     
#   }
#   GO_multiple_cell_type$GO_description <- with(GO_multiple_cell_type, 
#                                                reorder(GO_description, corresponding_GeneRatio))
#   
#   
#   
#   # draw dot plot for all cell types that have significant GO terms
#   p1 <- ggplot(data = GO_multiple_cell_type, aes(x = cell_type, y = GO_description, 
#                                                  color = `min_p.adjust`, size = corresponding_GeneRatio)) + 
#     geom_point() +
#     scale_color_gradient(low = "red", high = "blue") +
#     scale_size_continuous(limits = c(min(GO_multiple_cell_type$corresponding_GeneRatio),
#                                      max(GO_multiple_cell_type$corresponding_GeneRatio)), range = c(3, 7)) + 
#     theme_bw() + 
#     ylab("") + 
#     xlab("") + 
#     ggtitle("GO enrichment dot plot per cell type")
#   
#   
#   png(filename=paste0('Results/', sampSet, '_', method,'_GO_dot_plot_mul_cell_types.png'), height=9000, width=4000, res = 300)
#   print(p1)
#   dev.off()
#   
#   
#   
#   library(dplyr)
#   
#   # Group by 'GO_ID' and count the number of unique cell types for each 'GO_ID'
#   shared_GO_IDs <- GO_multiple_cell_type %>%
#     group_by(GO_ID) %>%
#     filter(n_distinct(cell_type) == 3)  # Only keep GO_IDs with all 3 cell types
#   
#   shared_GO_IDs$GO_description <- with(shared_GO_IDs, 
#                                        reorder(GO_description, corresponding_GeneRatio))
#   head(shared_GO_IDs)
#   write.table(shared_GO_IDs, paste0("Results/", sampSet, "_BP", "_edgeR_GO_dotplot_combined_shared.tsv"), sep="\t", quote=FALSE, row.names = FALSE)
#   
#   
#   
#   p1 <- ggplot(data = shared_GO_IDs, aes(x = cell_type, y = GO_description, 
#                                          color = `min_p.adjust`, size = `corresponding_GeneRatio`)) + 
#     geom_point() +
#     scale_color_gradient(low = "red", high = "blue") +
#     theme_bw() + 
#     ylab("") + 
#     xlab("") + 
#     ggtitle("shared GO enrichment dot plot per cell type")
#   
#   # print(p1)
#   png(filename=paste0('Results/', sampSet, '_', method, '_GO_dot_plot_mul_cell_types_shared.png'), height=1080, width=1080, res = 120)
#   print(p1)
#   dev.off()
#   
# }






```

<!-- ```{r use enrichGO to plot individual GO dot plot for each cluster in edgeR DE results, fig.width= 8, fig.height=16} -->

<!-- # -->
<!-- # # Load libraries -->
<!-- # library(DOSE) -->
<!-- # library(pathview) -->
<!-- # library(clusterProfiler) -->
<!-- # library(org.Ss.eg.db) -->
<!-- # -->
<!-- # method = "edgeR" -->
<!-- # if(method == "edgeR") -->
<!-- # { -->
<!-- #    file_list <- list.files(path = "v1.10/Results/", pattern = "run_2_edgeR_DE_cluster_.*\\.csv", full.names = TRUE) -->
<!-- # } -->
<!-- # -->
<!-- # -->
<!-- # for (file_path in file_list) -->
<!-- # { -->
<!-- # res_ids = read.csv(file_path, header=TRUE) -->
<!-- # if(method == "edgeR") -->
<!-- # { -->
<!-- # -->
<!-- # -->
<!-- #   ## Create background dataset for hypergeometric testing using all genes tested for significance in the results -->
<!-- #   allOE_genes <- as.character(res_ids$symbol) -->
<!-- # -->
<!-- #   ## Extract significant results -->
<!-- #   sigOE <- dplyr::filter(res_ids, p_adjust < 0.05) -->
<!-- #   head(sigOE) -->
<!-- #   sigOE_genes <- as.character(sigOE$symbol) -->
<!-- # -->
<!-- # }else if(method == "nebula") -->
<!-- # { -->
<!-- #   res_ids = read.csv("Results/run_1_DE_nebula_CD8T.csv", header=TRUE) -->
<!-- # -->
<!-- #   ## Create background dataset for hypergeometric testing using all genes tested for significance in the results -->
<!-- #   allOE_genes <- as.character(res_ids$ID) -->
<!-- # -->
<!-- #   ## Extract significant results -->
<!-- #   sigOE <- dplyr::filter(res_ids, adj.P.Val < 0.0005) -->
<!-- #   head(sigOE) -->
<!-- #   sigOE_genes <- as.character(sigOE$ID) -->
<!-- # -->
<!-- # } -->
<!-- # # some significant DE genes have low fold change, so not be considered up or down, -->
<!-- # # so length of sigOE_genes is not equal to the sum of up+down -->
<!-- # if(length(sigOE_genes) > 0) -->
<!-- # { -->
<!-- #   # print(paste0("enough DE genes",length(sigOE_genes), file_path)) -->
<!-- # ## Run GO enrichment analysis -->
<!-- # ego <- enrichGO(gene = sigOE_genes, -->
<!-- #                 universe = allOE_genes, -->
<!-- #                 keyType = "SYMBOL", -->
<!-- #                 OrgDb = org.Ss.eg.db, -->
<!-- #                 ont = "BP", -->
<!-- #                 pAdjustMethod = "fdr", -->
<!-- #                 qvalueCutoff = 0.05, -->
<!-- #                 readable = TRUE) -->
<!-- # -->
<!-- # -->
<!-- # ## Output results from GO analysis to a table -->
<!-- # cluster_summary <- data.frame(ego) -->
<!-- # -->
<!-- # # print(head(cluster_summary)) -->
<!-- # # write.csv(cluster_summary, "test.csv") -->
<!-- # if(nrow(cluster_summary) > 0) -->
<!-- # { -->
<!-- #   p1 <- dotplot(ego, showCategory=50) -->
<!-- #   print(p1) -->
<!-- #   # png(filename='test.png', height=1500, width=700) -->
<!-- #   # print(p1) -->
<!-- #   # dev.off() -->
<!-- # }else -->
<!-- # { -->
<!-- #   print(paste("fail to draw GO dot plots, since 0 enriched GO found", file_path)) -->
<!-- # -->
<!-- # } -->
<!-- # -->
<!-- # }else -->
<!-- # { -->
<!-- #   print(paste("fail for GO enrichment analysis, since DE genes number less than 0", file_path)) -->
<!-- # -->
<!-- # } -->
<!-- # -->
<!-- # } -->
<!-- # -->
<!-- # -->
<!-- # -->
<!-- # -->

<!-- ``` -->



<!-- ```{r using gseGO to plot GO activated and depressed dot plots, Network plot for nebula DE results, fig.width= 12, fig.height=12} -->

<!-- # sce_all <- readRDS(paste0('sce_',sampSet,'_with_subcluster.rds')) -->
<!-- # sce_all_corrected <- readRDS(paste0('sce_',sampSet,'_corrected_with_subcluster.rds')) -->
<!-- # df <- read.csv("Results/run_1_DE_nebula_CD8T.csv", header=TRUE) -->
<!-- # CSV file containing a list of gene names and log2 fold change values. This data is typically produced by differential expression analysis tool  -->
<!-- # method <- "nebula" -->
<!-- # selected_subset <- "CD8T" -->
<!-- # paste0("Results/run_1_DE_", method, '_', selected_subset, ".csv") -->

<!-- # library(clusterProfiler) -->
<!-- # library(enrichplot) -->
<!-- # # we use ggplot2 to add x axis labels (ex: ridgeplot) -->
<!-- # library(ggplot2) -->


<!-- # # we want the log2 fold change  -->
<!-- # original_gene_list <- as.numeric(df$logFC) -->
<!-- #  -->
<!-- # # name the vector -->
<!-- # names(original_gene_list) <- df$ID -->
<!-- # # omit any NA values  -->
<!-- # gene_list<-na.omit(original_gene_list) -->
<!-- # # sort the list in decreasing order (required for clusterProfiler) -->
<!-- # gene_list = sort(gene_list, decreasing = TRUE) -->
<!-- # head(gene_list) -->
<!-- #  -->
<!-- #  -->
<!-- # # SET THE DESIRED ORGANISM HERE -->
<!-- # organism = "org.Ss.eg.db" -->
<!-- # # BiocManager::install(organism, character.only = TRUE) -->
<!-- # library(organism, character.only = TRUE) -->
<!-- #  -->
<!-- # keytypes(org.Ss.eg.db) -->
<!-- #  -->
<!-- # gse <- gseGO(geneList=gene_list,  -->
<!-- #              ont ="ALL",  -->
<!-- #              keyType = "SYMBOL",  -->
<!-- #              minGSSize = 3,  -->
<!-- #              maxGSSize = 800,  -->
<!-- #              pvalueCutoff = 0.05,  -->
<!-- #              verbose = TRUE,  -->
<!-- #              OrgDb = organism,  -->
<!-- #              pAdjustMethod = "fdr") -->
<!-- # # Warning messages: -->
<!-- # # 1: In preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam,  : -->
<!-- # # There are duplicate gene names, fgsea may produce unexpected results. -->
<!-- # # 2: In fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize,  : -->
<!-- # # There were 2 pathways for which P-values were not calculated properly due to unbalanced (positive and negative) gene-level statistic values. For such pathways pval, padj, NES, log2err are set to NA. You can try to increase the value of the argument nPermSimple (for example set it nPermSimple = 10000) -->
<!-- # # 3: In fgseaMultilevel(pathways = pathways, stats = stats, minSize = minSize,  : -->
<!-- # # For some of the pathways the P-values were likely overestimated. For such pathways log2err is set to NA. -->
<!-- #                                                                              -->
<!-- #  -->
<!-- # require(DOSE) -->
<!-- # p1 <- dotplot(gse, showCategory=10, split=".sign") + facet_grid(.~.sign) -->
<!-- # print(p1) -->
<!-- # # png(filename='GO_sign_dot_plot.png', height=1080, width=1080) -->
<!-- # # print(p1) -->
<!-- # # dev.off() -->
<!-- #  -->
<!-- # # Assuming 'gse' is the result of enrichment analysis (e.g., from gseGO, gseKEGG, etc.) -->
<!-- # gse <- pairwise_termsim(gse)  # Compute the term similarity matrix -->
<!-- # p1 <- emapplot(gse, showCategory = 10) -->
<!-- # print(p1) -->
<!-- # # png(filename='GO_Enrichment_map.png', height=1080, width=1080) -->
<!-- # # print(p1) -->
<!-- # # dev.off() -->
<!-- #  -->
<!-- # # categorySize can be either 'pvalue' or 'geneNum' -->
<!-- # p1 <- cnetplot(gse, categorySize="pvalue", foldChange=gene_list, showCategory = 3) -->
<!-- # print(p1) -->
<!-- # # png(filename='GO_gene_network.png', height=1080, width=1080) -->
<!-- # # print(p1) -->
<!-- # # dev.off() -->
<!-- #  -->

<!-- ``` -->



# Wrapping up

Save everything

```{r save rds}

#
save.image(file = paste0('enrichment_analysis_',sampSet,'.RData'))
sessionInfo()
# saveRDS(sce_all_filt, file=paste0('sce_',sampSet,'_cluster_filt.rds'))




```

