---
title: "test_sub-cluster"
author: "lily"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = TRUE}
knitr::opts_chunk$set(echo = TRUE)

bsp_num <- Sys.getenv("bsp_num")
clustK <- Sys.getenv("clustK")
sampSet <- Sys.getenv("sampSet")

```


```{r prepare the environment}
getwd()
# setwd("/mnt/rstudio/lily/bsp248")
setwd("/mnt/lustre/RDS-ephemeral/bioinformatics/analysis/scrna/proj/bsp_248/lily/stages")

load('clustering_develop_code.RData')


library(SingleCellExperiment)
library(DropletUtils)
library(scran)
library(scater)
library(uwot)
library(biomaRt)
library(scds)
library(batchelor)
library(ggplot2)
library(ggbeeswarm)
library(scater)

sce_corrected = readRDS(file = paste0('sce_',sampSet,'_corrected_initial_cluster.rds'))

sce = readRDS(file = paste0('sce_',sampSet,'_initial_cluster.rds'))

selected_sce <- sce_corrected

UMAP_color_by_cluster <- function(selected_sce, title_flag = "batch effect corrected" )
{
  set.seed(55698)
  umap_plot <- plotUMAP(selected_sce, colour_by="cluster", point_size=0.3,text_by = "cluster") + guides(colour = guide_legend(override.aes = list(size=6))) + ggtitle(paste(sampSet, title_flag))
  # Adjust the legend text and title size
  
  
  # Print the plot
  print(umap_plot)
  
  
  TSNE_plot <- plotTSNE(selected_sce, colour_by="cluster", point_size=0.3,text_by = "cluster") + guides(colour = guide_legend(override.aes = list(size=6))) + ggtitle(paste(sampSet, title_flag))
  # print(TSNE_plot)  
}


UMAP_color_by_cluster(sce_corrected, "batch effect corrected" )
```


```{r reclustering selected clusters}
cluster_n <- c("5", "14", "16", "15") 

  library(scran)
guided_unsupervised_recluster <- function(sce, cluster_n = '8',n_HVG = 1000, k_value = 20)
{
  selected_cells <- (sce$cluster %in% cluster_n)
  print(table(selected_cells))
  
  # CD4 <- counts(sce)['ENSSSCG00000000687',selected_cells]
  # # the CD4 gene counts of all cells in selected cluster 
  # CD8 <- counts(sce)['ENSSSCG00000008213',selected_cells]
  # # the CD8B gene counts of all cells in selected cluster 

  # extract all cells in selected clusters, and get the top 1000 (n_HVG) HVG in these cells
  varmod8 <- modelGeneVar(sce[,selected_cells], block=sce[,selected_cells]$run)
  vargenes8 <- getTopHVGs(varmod8, n=1000)
  
  CD4corr <- vector('numeric', 1000)
  CD8corr <- vector('numeric', 1000)
  KLRK1_corr <- vector('numeric', 1000)
  KLRB1_corr <- vector('numeric', 1000)
  
  library(scHOT)
  if(file.exists("recluster_CD4corr.rds") & 
     file.exists("recluster_CD8corr.rds") & 
     file.exists("recluster_KLRK1_corr.rds") &
     file.exists("recluster_KLRB1_corr.rds"))
  {
    CD4corr = readRDS(file = "recluster_CD4corr.rds")
    CD8corr = readRDS(file = "recluster_CD8corr.rds")
    KLRK1_corr = readRDS(file = "recluster_KLRK1_corr.rds")
    KLRB1_corr = readRDS(file = "recluster_KLRB1_corr.rds") 
    
  }else
  {  
    for(i in 1:length(vargenes8)){
      
      # the weightedZIKendall function calculates weighted Tau*, where Tau* is described in Pimentel et al (2015). This association measure is defined for zero-inflated, non-negative random variables.
      CD4corr[i] <- weightedZIKendall(logcounts(sce)['ENSSSCG00000000687', selected_cells],
                                      logcounts(sce)[vargenes8[i], selected_cells])
      # # calculate numeric weighted Tau* association value between gene CD4 and each HVG
      # 
      # #   ‘exprs(sce)['ENSSSCG00000000687', selected_cells]’ is the log counts of gene CD4 in selected cells.
      # # ‘exprs(sce)[vargenes8[i], selected_cells]’ is the log counts of one of the HVG gene in selected cells
      CD8corr[i] <- weightedZIKendall(logcounts(sce)['ENSSSCG00000008213', selected_cells],
                                      logcounts(sce)[vargenes8[i], selected_cells])
      # calculate numeric weighted Tau* association value between gene CD8 and each HVG
      
      KLRK1_corr[i] <- weightedZIKendall(logcounts(sce)['ENSSSCG00000040465', selected_cells],
                                         logcounts(sce)[vargenes8[i], selected_cells])
      KLRB1_corr[i] <- weightedZIKendall(logcounts(sce)['ENSSSCG00000039708', selected_cells],
                                         logcounts(sce)[vargenes8[i], selected_cells])      
    }
    
 
    
    saveRDS(CD8corr, file = "recluster_CD8corr.rds")
    saveRDS(CD4corr, file = "recluster_CD4corr.rds")
    saveRDS(KLRK1_corr, file = "recluster_KLRK1_corr.rds")
    saveRDS(KLRB1_corr, file = "recluster_KLRB1_corr.rds")    
    
  }

  # select HVGs who positively co-expressed with CD4 and CD8  or have little to no monotonic association with CD4 and CD8 in cells in cluster 8
  
  # select HVGs whose association value with CD4 and CD8 both higher than 0.1
  # A value close to 1 indicates a strong positive association, meaning that as the expression of CD4 increases, the expression of the HVG also tends to increase across the selected cells
  # - **Value Close to Zero**: Indicates little to no monotonic association between the expression levels of the two genes.

  KLRK1_corr <- KLRK1_corr[1:1000]
  related_genes <- unique(c(which(CD4corr > 0.1), which(CD8corr > 0.1),
                            which(KLRK1_corr > 0.1), which(KLRB1_corr > 0.1)))
  top <- vargenes8[related_genes]
  print("which(CD4corr > 0.1)")
  print(which(CD4corr > 0.1) )
  print("which(CD8corr > 0.1)")
  print(which(CD8corr > 0.1) )  
  print("which(KLRK1_corr > 0.1)")  
  print(which(KLRK1_corr > 0.1) )
  print("which(KLRB1_corr > 0.1)")
  print(which(KLRB1_corr > 0.1) )  
  

  top <- c(top, 'ENSSSCG00000000687', 'ENSSSCG00000008213',
           "ENSSSCG00000039708", 'ENSSSCG00000040465' , 'ENSSSCG00000040140')
  # 
  top <- unique(top)  
  print(paste("length(top)", length(top)))  

  
  # we don't batch correct there, but only use fastMNN to reduce the genes we use for draw UMAP for those selected cells
  library(batchelor)
  set.seed(100)
  sce_8_fastMN_UMAP <- fastMNN(sce[,selected_cells], batch=sce[,selected_cells]$run,
                           subset.row = top, get.variance = TRUE)
  sce_8_fastMN_UMAP <- runUMAP(sce_8_fastMN_UMAP, dimred="corrected")
  p <- plotUMAP(sce_8_fastMN_UMAP, colour_by="batch", point_size=1) 
  print(p)  
  
  
  # we now only select marker genes we're interested as input for the re-clustering
  related_genes <- unique(c(which(CD4corr > 0.1), which(CD8corr > 0.1)))
  top <- vargenes8[related_genes]  
  
  top <- c(top, 'ENSSSCG00000000687', 'ENSSSCG00000008213',
         "ENSSSCG00000039708", 'ENSSSCG00000040465' , 'ENSSSCG00000040140')
  print("gene used for re-clustering")
  print(top)
  if (length(top) < 5)
  {
    print('reminding: less than 5 related genes used for guided unsupervised clustering')
  }
  set.seed(100)
  sce_8_fastMNN <- fastMNN(sce[,selected_cells], batch=sce[,selected_cells]$run,
                           subset.row = top, get.variance = TRUE)
  library(bluster)
  library(scran)
  library(scater)
  set.seed(200)
  print(k_value)
  sce_8_fastMNN_clust <- clusterCells(sce_8_fastMNN,use.dimred="corrected",
                                      BLUSPARAM=SNNGraphParam(k = k_value, 
                                                              type="jaccard",
                                                              cluster.fun="fast_greedy"))
# k=100 is the final decided value
  # check the number of cells in each new cluster, and add new cluster annotation to sce_8_fastMN_UMAP
  print(table(sce_8_fastMNN_clust))
  
  
  sce_8_fastMN_UMAP$cluster <- sce_8_fastMNN_clust
  p <- plotUMAP(sce_8_fastMN_UMAP, colour_by="cluster", point_size=1) + ggtitle(' cluster')
  p <- p + guides(colour = guide_legend(override.aes = list(size=6)))
  print(p)

  # add necessary log-counts and gene id, symbol metadata into sce_8_fastMN_UMAP
  assays(sce_8_fastMN_UMAP)$logcounts <- assays(sce)$logcounts[rownames(sce_8_fastMN_UMAP), selected_cells]

  rowdat <- rowData(sce_8_fastMN_UMAP)
  head(rowData(sce))
  rowdat <- cbind( rowData(sce)[rownames(sce_8_fastMN_UMAP), ], rowdat )
  rowData(sce_8_fastMN_UMAP) <- rowdat      

  
  # draw the UMAP plots to check the selected genes expression in UMAP 
  for(selected_gene in c("CD4", "CD8B",  "KLRB1", "KLRK1", "CD3E"))
  {
    print(selected_gene)
      selected_gene_id <- rownames(sce)[rowData(sce)$Symbol == selected_gene]
      p <- plotUMAP(sce_8_fastMN_UMAP, colour_by=selected_gene_id, by_exprs_values='logcounts') + 
        ggtitle(selected_gene) 
      print(p)
  }

  # draw the violin plots to check the selected genes expression across new clusters 
  selected_genes <- rownames(sce)[rowData(sce)$Symbol %in% c("CD4", "CD8B",  "KLRB1", "KLRK1", "CD3E")]
  library(scater)
  p <- plotExpression(sce_8_fastMN_UMAP, features=selected_genes, x='cluster',
                      exprs_values='logcounts')   
  print(p)
  for(selected_gene in c("CD4", "CD8B",  "KLRB1", "KLRK1", "CD3E"))
  {
    selected_gene_id <- rownames(sce)[rowData(sce)$Symbol == selected_gene]
    print(paste(selected_gene, selected_gene_id))
  }

  
  # save.image("clustering_develop_code2.RData")
  #################################################
  # # Ensure sce_8_fastMNN_clust  is a character vector
  # sce_8_fastMNN_clust  <- as.character(sce_8_fastMNN_clust )
  # 

  # # # add new sub cluster annotation to sce
  # 
  # # Loop through the numbers and assign labels
  # subcluster_vector <- NULL
  # for (i in 1:length(unique(sce_8_fastMNN_clust ))) {
  #   sce_8_fastMNN_clust [sce_8_fastMNN_clust  == as.character(i)] <- paste0(cluster_n, letters[i])
  #   subcluster_vector <- c(subcluster_vector,paste0(cluster_n, letters[i]))
  # }
  # 
  # # This will assign new sub-cluster '1' as '12a', '2' with '12b', ..., '5' with '12e', ...
  # 
  # 
  # cs <- as.character(sce$cluster)
  # cs[selected_cells] <- sce_8_fastMNN_clust
  # sce$cluster <- cs
  # check_sample_contribution_location_for_selected_subcluster(sce,subcluster_vector)
  # 
  saveRDS(sce_8_fastMN_UMAP, file = "r_shiny_sce_8_fastMNN.rds") 
  return(sce_8_fastMN_UMAP)
}
print(clustK)
sce_test <- guided_unsupervised_recluster(sce, cluster_n, n_HVG = 5000, k_value = clustK)


```
